name: health_app
description: A simple health tracker app that stores user profile data.
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0 # Saves user data locally
  fl_chart: ^0.63.0
  huggingface_dart: ^0.0.2
  huggingface_client: ^1.6.1
  flutter_health_connect: ^1.2.3
  health: ^12.0.1
  permission_handler: ^11.4.0
  carp_serializable: ^2.0.0
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.2.1
  flutter_smart_watch: ^1.0.0
  flutter_reactive_ble: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any # Ensures best coding practices

flutter:
  uses-material-design: true
  assets:
    - .env
